# Generated by Django 2.0.7 on 2018-07-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=20)),
                ('market_cap', models.IntegerField()),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('delta', models.FloatField(default='')),
                ('current_coin_value', models.FloatField(default='')),
                ('email', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default='')),
            ],
        ),
    ]
