# Generated by Django 2.0.7 on 2018-07-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_auto_20180707_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noftification',
            new_name='Notification',
        ),
    ]
